### ISSUE TITLE
Travis CI Tracking Issue

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1101]
Improve the CI build process.

- [x] Print diff logs on Travis (while maintaining logging to files during development) #1105
- [x] Try building TeX in CI
- [x] Try compiling code in CI

**Comment by Mornix** [comment]
Completed with merge of #1466. Closing.
