### ISSUE TITLE
CodeGen Tracking Issue

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1178]
This issue is cataloguing existing issues with the codegen required to get GlassBR and NoPCM code building and running. 

I know @JacquesCarette and @smiths dislike long-standing issues but I think cataloguing a list of smaller outstanding issues is a worthwhile tracking issue.

Outstanding issues:
- [x] #1177  —  Function location is hardcoded and breaks with structure being `Loose`.
- [x] #1179  —  Function location is hardcoded and breaks sometimes. (Works for generated GlassBR).
- [x] #1180  —  Lack of Makefiles (Nice to have).
- [x] #1183  —  Python ternaries are incorrect.
- [x] #1184  —  Integer conditionals incorrectly generated.
- [x] #1453   —  Loose input structure option leads to broken code

**Comment by JacquesCarette** [comment]
Agreed on both points (not like in general, good idea here).

**Comment by bmaclach** [comment]
All GlassBR and NoPCM generated code now compiles, so I think this issue can be closed.
