### ISSUE TITLE
Add/Reference Properties of Correct Solution

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1276]
![NFR!](https://user-images.githubusercontent.com/35857611/57247551-2a1e6980-700e-11e9-8a3e-38e038eef3f6.png)
![propsOfCorrectSol](https://user-images.githubusercontent.com/35857611/57247603-49b59200-700e-11e9-9af9-39a1d941e33e.png)

(from #1229) - the Properties of Correct Solution section is referenced by `Correctness`, but does not exist. It should be added to the example with correct referencing. (Use the section from SWHS as inspiration.)

_Filling in of section moved to #1302._

# TODO:
- [x] Add to SSP and reference (#1279)
- [x] Add to NoPCM and reference in SWHS and NoPCM (#1282)
- [x] Add to GlassBR and reference (#1300)
- [x] Add to Chipmunk and reference (#1321)

**Comment by samm82** [comment]
@smiths Is a placeholder FIXME enough for now, or should I try to come up with some correct solution properties?

**Comment by smiths** [comment]
@samm82, if you can come up with properties of a correct solution that would be great.  I'd be very happy to discuss your ideas.

**Comment by samm82** [comment]
@smiths Since NoPCM is a simpler version of SWHS, I thought I'd ask - should NoPCM have the section as well, since it has the same NFR that references it as SWHS? My thought is yes, but just double checking. 😁

**Comment by smiths** [comment]
Yes, NoPCM should have this section.  The section (Properties of a Correct Solution) is part of the SRS template.  All examples should have it, even if the content for the section is to say there are no known properties (other than satisfying the requirements).
