### ISSUE TITLE
Requirements not Reused between SWHS and NoPCM

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1281]
(Came from working on #1229 and #1276)

There are a lot of similar (almost) identical functional requirements that are defined individually in SWHS and NoPCM and should be reused. There are also some discrepancies from the manual, as described in #439 that should be fixed in both examples (if/when applicable).

# TODO
_In branch `swhsNoPCMReqs`_
- [x] Input-Initial-Quantities
    - [x] Move assumption from Input-Initial-Quantities to Find-Mass
    - [x] ~~Add quantities to table~~ (#1307)
- [x] Find-Mass
    - [x] Add "^2" to equation
    - [x] ~~Add "pi" to equation~~ (#1308)
- [x] Check-Input-with-Physical_Constraints
- [x] Output-Input-Derived-Quantities
- [x] Calculate-Temperature-Water-Over-Time
- [x] Calculate-Change-Heat_Energy-Water-Over-Time
- [x] Move NoPCM requirements to separate file

**Comment by samm82** [comment]
@smiths I'm assuming that the FRs aren't placeholders at this point - is this a valid issue @smiths?

**Comment by smiths** [comment]
Yes, this is a valid issue.  The two examples should share many requirements.  You might want to talk to @bmaclach, since he recently verified that the two examples share the same goal statements.

**Comment by samm82** [comment]
@smiths Is the assumption here (in the first FR of SWHS) really necessary? This FR only deals with inputting the values, and this assumption seems to apply more to calculations. This assumption and its reference aren't in NoPCM.

![swhsFR1](https://user-images.githubusercontent.com/35857611/57478928-36066780-726a-11e9-85d5-a02fe0641d35.png)

**Comment by samm82** [comment]
@smiths Also, the table in Drasil for FR1 is missing these quantities:
![image](https://user-images.githubusercontent.com/35857611/57481450-2853e080-7270-11e9-98e3-bb913f6e848e.png)

**Comment by samm82** [comment]
(I think I should have kept #439 open 😬)

This equation is wrong in Drasil:
![image](https://user-images.githubusercontent.com/35857611/57481598-7537b700-7270-11e9-8f82-8ca31c047d80.png)

**Comment by smiths** [comment]
@samm82, try to keep one topic per issue.  It makes it easier to address your questions, and it should lead to closing the easy issue quickly.

For your first sub-issue (unnecessary assumption), if you look at the manual case study (https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf) you will see that a mistake was made in translating from manual to Drasil.  It is really a shame that mistakes like this are still cropping up.  😞  The assumption that the volume is negligible goes with the `Find-Mass` requirement.  If you look at the derivation it assumes that the mass of the water is based on the volume of the water, which is calculated from the volume of the tank, minus the volume of the PCM.  Technically the coil volume should also be subtracted, but the assumption means that we can ignore this.  Please move the assumption to be with the correct requirement.

For your second sub-issue, you should add the missing inputs to the table of input variables.

For your third sub-issue, you are also correct that Drasil has the wrong formula.  I think this is just a mistake with someone entering the formulae.  I don't believe we have "taught" Drasil the volume formulas yet.
