### ISSUE TITLE
Create drasil-database Package

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1294]
As mentioned in #918, the `drasil-database` subpackage should be created with the code that deals with "'database' aspects of information collection."

## TODO
- [x] Move Language.Drasil.ChunkDB (#1306)
- [x] Move Language.Drasil.ChunkDB.GetChunk (#1306)
- [x] Move Language.Drasil.SystemInformation (#1306)
- [x] Add to wiki page

**Comment by samm82** [comment]
If `Language.Drasil.SystemInformation` uses `ChunkDB`, does it make sense to move it to `drasil-database` as well? @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes.

**Comment by samm82** [comment]
@JacquesCarette Done in #1306.
