### ISSUE TITLE
Create drasil-utils SubPackage

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1390]
As per comments on #1388, there should be a `drasil-utils`. The file structure will be:
```
+ Utils.Drasil
| --- Fold.hs (contains folde, foldlList, foldlSent_, etc. from SentenceStructures)
| --- Misc.hs (everything else until we re-allocate them)
| --- Phrase.hs (phrase builders)
| --- Sentence.hs (sentence constructors like sAnd, ofThe, etc. from SentenceStructures)
```

# TODO
- [x] Move marked functions from SentenceStructures.hs to `Utils.hs` (#1411)
- [x] Make Sentence in `utils` (#1436)
- [x] Move Phrase to `utils` (#1470)
- [x] Make Fold in `utils` (SentenceStructures) (#1448)
- [x] Make Misc in `utils` (Utils) (#1510)
- [x] Move rest of SentenceStructures to Misc (#1544)
- [x] `printers` should depend on `utils` now, not `data` (#1448)
- [x] Update Wiki

**Comment by JacquesCarette** [comment]
If it is going to be mostly filled with utilities to deal with `Sentence`s, it's tempting to call it `drasil-english`. If it's a mixture of generic Haskell code and other things, `-utils` is probably right.

And yes, many of the things in `SentenceStructures.hs` are not really in the right place.

**Comment by samm82** [comment]
Most functions create a `Sentence`; the only exceptions are `figureLabel` that creates a `LabelledContent` (marked with a FIXME wondering if it's in the right file) and the term formatters that return an `ItemType` (`tAndDWAcc`, tAndDWSym` and  `tAndDOnly`).

There is also a section of functions at the bottom marked "TO BE MOVED TO EXAMPLE/DRASIL/SECTIONS", which is now `docLang`, so I'll move those to there.

**Comment by JacquesCarette** [comment]
The stuff that generates pieces of documents should all go into `docLang` for now.

**Comment by samm82** [comment]
There already exists a `Data.Drasil.Utils`. Should this, and `Data.Drasil.SentenceStructures` (once all functions unrelated to `Sentence`s are removed) both be moved to `drasil-utils`?

**Comment by samm82** [comment]
Also, instead of moving these functions to `docLang`, I'm moving them to `Utils.hs`, since they have potential to easily be reused at some point in the future. (If that's OK with you @JacquesCarette)

**Comment by samm82** [comment]
@JacquesCarette Can you review my changes in the `utils` branch and see if you like the direction I went with it?

**Comment by JacquesCarette** [comment]
I looked - it seemed fine. This is an incremental process, as we learn, we'll figure out where the best home for various things is.

**Comment by samm82** [comment]
Would a good file structure be something like
```
+ Utils.Drasil
| --- Utils.hs
| --- SentenceStructures.hs
```

with everything exported in `Utils.Drasil`? @JacquesCarette

**Comment by samm82** [comment]
@JacquesCarette It also looks like `Data.Drasil.Phrase` contains a lot of functions that could also be migrated.

**Comment by samm82** [comment]
I think I'm going to go ahead on this:
```
+ Utils.Drasil
| --- Fold.hs (contains folde, foldlList, foldlSent_, etc. from SentenceStructures)
| --- Misc.hs (everything else until we re-allocate them)
| --- Phrase.hs (phrase builders)
| --- Sentence.hs (sentence constructors like sAnd, ofThe, etc. from SentenceStructures)
```

**Comment by JacquesCarette** [comment]
I concur, that is a good arrangement. And yes to moving other items like you have.

**Comment by samm82** [comment]
@JacquesCarette  Some notes about removing imports from `Utils.hs` because they cause issues:
1) `fterms` is just imported from `Data.Drasil.Concepts.Documentation`, not used, and then exported. Is there a design decision behind this or can I remove it from the import list?
2) `prodUCTbl` is never used in Drasil:
https://github.com/JacquesCarette/Drasil/blob/6e7a37d90e34355a21a7569066e56c490db01e22/code/drasil-data/Data/Drasil/Utils.hs#L183-L186
Should it be removed? Further investigation shows that the use case table has been completely removed from all examples (I even used to have an issue about the one in GlassBR - #833), and I can't find an issue for it. Was this intentional?
3) The separate issue #1440 should also be addressed before proceeding on this one.

**Comment by smiths** [comment]
Yes, `prodUCTbl` should be removed.  In the revisions that @vajihehm and I did to GlassBR we removed it.  It was a mistake to have use cases in the GlassBR documentation.  It was worth exploring, but it doesn't add anything to the documentation, at least not in any of our examples.  There is one use case for all of our examples: input data, calculate results, output results.  This use case is explicit in our documentation through the requirements.  It would be redundant to say it again.

**Comment by JacquesCarette** [comment]
Go ahead and move `fterms`. Hopefully #1440 is easy.
In our current vision of things, `utils` should not depend on `data` as packages. Do note that `drasil-lang` contains part of the `Data.Drasil` hierarchy (by design), which is slightly different.
