### ISSUE TITLE
Improve Formatting from Projectile

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1575]
The review of Projectile uncovered a lot of formatting issues that should be cleaned up. This is a master issue for tracking all formatting issues, with smaller issues being created for discussion/questions if necessary.

- [x] Remove unnecessary blurb from Assumptions section (#1576)
- [x] Add "The assumptions refine the scope by providing more detail." to assumption intro (#1576)
- [x] Fix display of RefBy in assumptions and chunks (using `foldlList`) (#1576)
- [x] Remove duplicate references with RefBy (#1576)
- [x] Remove reference to the solution from ProbDesc using PDProg (#1576)
- [ ] Format derivations better (with a bold (automated?) header and newline) (#1636)
- [ ] Shorten up/automate chunk names (ie. IM1, IM2) (possibly covered in #1539)
- [ ] Reference figures by number (ie. Figure 1)
- [ ] Extract typing information for vectors (#1558) | _related_ Fix units of vectors
- [ ] Make column wider in IMs to have "Output Constraints" on one line
   - @smiths Could we make it shorter to force it to two lines? I think this would be neater and more space-efficient since the constraints section is always more than one line tall (at least in the LaTeX - this might not be the greatest idea for the HTML).
- [ ] Display variable names better in LaTeX (using `\mathit{}` or `\text{}`)
- [x] Fix formatting of `Perc` constructor for `Expr` (#1583)
- [ ] Bold table headings in LaTeX
- [ ] Check spacing in derivatives

**Comment by samm82** [comment]
Split into smaller issues
