### ISSUE TITLE
Update Quick Start Guide

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3056]
# TODO:
- [x] Modify MinGW warning in Quick Start Guide?
- [x] Add instructions for if Windows Security blocks/removes stack.exe to Quick Start Guide
- [x] Add instructions for if Windows Security blocks/removes stack.exe to New Workspace Setup
- [x] Add util-linux-ng installation instructions to New Workspace Setup

**Comment by balacij** [comment]
If I remember correctly, MinGW might have been missing `rev`, but I know Cygwin installs it. Does your installation have it?

Related: https://github.com/JacquesCarette/Drasil/issues/2642#issuecomment-1023842307

**Comment by samm82** [comment]
@balacij I found that `rev` (and some other utilities like `whereis`) can be installed for Windows through [util-linux-ng](http://gnuwin32.sourceforge.net/packages/util-linux-ng.htm), and they work with MinGW (once added to the PATH). Presumably documenting this in the Quick Start Guide would be sufficient? I'm curious to know where we use `rev` in Drasil!

**Comment by balacij** [comment]
It's used in the `scripts/` folder, but it's not necessarily "essential". It is used somewhere that someone will eventually, but uncommonly, find issue with.

To be honest, I think it would be best to remove MinGW from the Quick Start Guide, leave it as just suggesting cygwin (which has `rev` and other tools needed). However, we should definitely add it in the [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) wiki page.

```
code/scripts/duplicate_string_find.sh
11:grep -rhEo --exclude-dir=./Drasil/code/stable --include \*.hs '".{5,100}"' ./Drasil/code | cut -c 2- | rev | cut -c 2- | rev | awk '++A[$0]==3,1000' | awk '/^"/ || /"$/ || !/"/' | sed 's/^/"/' | sed 's/$/"/' > duplicate_strings.txt

code/scripts/deploy_stage.sh
129:        ls -d "$(cd "$CUR_DIR" && git rev-parse --show-toplevel)/$p"*/ | rev | cut -d/ -f2 | rev | tr '\n' '\0' | xargs -0 printf "$p%s\n" >> "$EXAMPLE_DEST$example_name/src"
```

**Comment by samm82** [comment]
I think we're dangerously close to bikeshedding here, but I personally think that having a brief line about MinGW in the Quick Start Guide would be beneficial, in case there are people with it already installed (like myself) who would like to use Drasil without installing Cygwin.
Regardless, I will definitely add a note about installing util-linux-ng in the New Workspace Setup guide. As my dad always says, "better to have it and not need it than need it and not have it!" Just to clarify, can Git Bash and MinGW be used interchangeably in this context? I'm a little fuzzy on what the differences between them actually are.

**Comment by JacquesCarette** [comment]
Having a section in there that's platform-specific, with advice of how to get things going on each platform, does sound quite sensible.

**Comment by smiths** [comment]
Agreed.

**Comment by balacij** [comment]
That's fine too :smile: 

I don't think Git Bash and MinGW are interchangeable, but I'm not 100% sure.

**Comment by samm82** [comment]
> I don't think Git Bash and MinGW are interchangeable, but I'm not 100% sure.

Based on [this StackExchange post](https://superuser.com/questions/1481401/how-to-understand-what-is-shell-terminal-mingw-bash-git-bash-etc), it seems like Git Bash uses MinGW, so I will update the Quick Start Guide to match

**Comment by samm82** [comment]
For completeness, this line has been modified in the New Workspace Setup:

> Git Bash is also very safe to use, but you will need to download [util-linux-ng](https://gnuwin32.sourceforge.net/packages/util-linux-ng.htm), which includes various system utilities (one of our scripts uses rev), and add its bin/ to your PATH.

and this section has been added to the Stack section: 

>##### Windows Security
>After installing/running Stack, you might notice that Windows Security blocks or even deletes the **stack.exe** executable. If this happens, add an exclusion to Windows Security by going to **Start > Settings > Update & Security > Windows Security > Virus & threat protection > Manage settings** (under **Virus & threat protection settings**) **> Add or remove exclusions** (under **Exclusions**), then selecting the **bin/** folder with your **stack.exe** file. If Windows Security deletes the executable, simply reinstall it. (This issue was encountered in Windows 10).
