### ISSUE TITLE
Move DDs that are outputs to be IMs in GlassBR

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3569]
The dependencies (e.g., what should be moved first) are listed in parenthesis. The last two items are not output DDs, but are required by other ones.

## TODO:
- [x] AR (J, $\hat{q}_\text{tol}$)
- [x] B (Pb)
- [x] GTF ($\hat{q}$, LR)
- [x] h (B, NFL, $\hat{q}$, Jtol)
- [x] J (B)
- [x] Jtol ($\hat{q}_\text{tol}$)
- [x] NFL (LR)
- [x] $\hat{q}$ (J)
- [x] $\hat{q}_\text{tol}$ (NFL)
- [x] Pb (IM1)
- [x] LR (IM2)

### Miscellaneous
- [x] Add constraints for $P_\text{b}$ and $P_\text{tol}$
- [x] Create issue for getting inputs and their constraints automatically (#3584)
- [x] Clean up imports

**Comment by samm82** [comment]
$a$ and $b$ have the following constraints:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/18d4f339-fc60-4b54-b59d-55a610fd5495)
Note that the relationship $a \geq b$ is captured twice, but this makes sense to make the constraints on each quantity self-contained.

Since IMs require their input constraints to be manually created (side note: this feels weird that this needs to be done manually; is there an issue open for it? should I make one if not?), I filled the input constraints of the $\mathit{AR} = a/b$ IM as:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/8b66f1a2-6397-4aed-8e85-633938809ab0)

This made sense to me, as it doesn't include redundant information unnecessarily; do you agree @smiths?

**Comment by smiths** [comment]
@samm82 I agree that the input constraints should appear both in the table and in the appropriate IM, but they should only be created once and re-used in the other context.

**Comment by samm82** [comment]
Currently, the inputs constraints pertaining to $P_\text{b}$ and $P_\text{tol}$ **in the IMs** are:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/4ac4a6cf-854a-4bf5-9998-7f20ca4087b4)
while **in the constraints table**, they are:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/1d6f1b73-0205-48f0-9248-00c78868abc0)
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/4dd3839e-8f9c-4aba-8e11-2d33718e285b)

Just double checking that the IM constraints should be updated to match the table constraints (another reason to automatically pull these constraints from their equations!)

**Comment by JacquesCarette** [comment]
Yes, those should match.
