### ISSUE TITLE
Report on the Devi branch

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#682]
There are some trivial and non-trivial issues with the diffs between build and stable on the Devi branch. It's had a lot of updates made to it over the last few months (and I managed to merge master in fairly recently), but was never fully merged in.

I'm going to continue removing the trivial diffs, but then I need some help on figuring out what exactly is going wrong (or going right, but looking different) and how to fix it (some are strictly printing issues for the IMs, some are a bit more complicated issues, in one case there's an entire subsection missing).

Could you please give me a breakdown of the diffs, along with which are (in your opinion) trivial, and which ones are larger problems? I've taken a good look at GlassBR for sure, so you can see the relatively small number of diffs left there after all is said and done.

If you all want to work on it, great, if not, please self-select someone to take this on.

**Comment by elwazana** [comment]
@szymczdm 

- GlassBR
    - Theoretical Models
        - Change in the descriptions (Non-trivial)
            -- Information is lost during the transition from paragraph form to bullet point form 
                **1.** If one of the TMs is true both are true if one is false both are false
                **2.** The glass is considered safe if either is true (because if one is true both are true as above)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41602828-ab1899e6-73a9-11e8-8f16-23eb143603f0.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41602868-bd6e80c4-73a9-11e8-9d16-6c063be93b63.png)

    - Data Definition
        - Change in the displaying of information (Trivial)
            -- Change in the format of equations (All DDs)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41603210-82ab0704-73aa-11e8-9724-411154c1dee6.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41603262-9dfd7e74-73aa-11e8-8ece-8421f6a8198c.png)
            --- Change in the format of the description of DD1
Stable:
![image](https://user-images.githubusercontent.com/35268928/41603397-dd7473be-73aa-11e8-9802-95c6dad6fbc3.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41603439-f29784b6-73aa-11e8-835e-9a421c8c5118.png)

    - Instance Models
        - Change in Description of IM2-IM3 (Non-trivial)
            -- Information is lost during the transition from paragraph form to bullet form
                **1.** Lose of associated assumptions
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41603946-005b589c-73ac-11e8-8b6f-02e5fe49a537.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41604027-3853246e-73ac-11e8-90f2-d05ad9888d94.png)

    - Data Constraints 
        - Missing entire subsection (Non-trivial)

**Comment by szymczdm** [comment]
That is excellent. I can already tell what needs to be updated :)

**Comment by elwazana** [comment]
@szymczdm I believe this is the last of the differences:

- Chipmunk
    - Specific System Description
        - Changed wording (Trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41608191-ed279a1a-73b5-11e8-8fbb-2537b14e9ef3.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608257-13b75c2e-73b6-11e8-93fd-b6ffb71dad17.png)

    - Solution Characteristics Specification
        - Added link (Trivial)
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41608315-3e43a178-73b6-11e8-8e9e-17e983dbfb78.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608351-52cbc1ca-73b6-11e8-8c75-ddcc72fec4b0.png)

    - Assumptions
        - Added links to various sections (DD, IM, TM, GenDefs, and LC) (Trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41608454-8ddd5a1c-73b6-11e8-9801-3126e27c066d.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608489-9cee23ce-73b6-11e8-89d1-82dc62869e27.png)
        - Semi-descriptive names added for actual assumptions (Trivial)
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41608563-c378995c-73b6-11e8-9363-a32d526a191c.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608645-ea603a16-73b6-11e8-9ee9-b5483cef64e6.png)
 
    - TMs 
        - Change in description (no significant lose of information) (Trivial) -> TM4
Stable:
![image](https://user-images.githubusercontent.com/35268928/41608894-8fb26494-73b7-11e8-840c-0156a2c9a799.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608919-a1c61126-73b7-11e8-99c5-13280a3612ae.png)
        - Change in description (Lose of information) (Non-Trivial) -> TM5
            **1.** Assumptions associated with TM removed
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41608824-6b1dca6a-73b7-11e8-89e0-65db4f7a2cc8.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41608870-7f172f02-73b7-11e8-84fd-2245e368b5c4.png)

    - GenDefs 
        - Section (used to be empty) -> Complete removal (Trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41609021-d8c04b6a-73b7-11e8-8117-36f3f9af895c.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41609036-e5d8cc8c-73b7-11e8-9bf6-a897da64ec33.png)

    - IMs 
        - Input/Output and input/output constraints added to tables (Trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41609179-34264a9a-73b8-11e8-8f10-5e43fb6f9443.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41609167-28b8ab4e-73b8-11e8-8c43-11d7e5d12648.png)
        - Information lost (Non-Trivial)
            **1.** Assumptions associated with IM removed
            **2.** Data Definitions associated with IM removed
Stable:
![image](https://user-images.githubusercontent.com/35268928/41609287-6f351f3a-73b8-11e8-9421-23734c6a1c7d.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41609326-8445dffe-73b8-11e8-8dd3-e165012d79ed.png)

    - DD
        - Missing Section (Non-Trivial)
    - Data Constraint
        - Missing Section (Non-Trivial)

**Comment by smiths** [comment]
Great summary @elwazana.  I agree with almost all of your conclusions.  However, there are a few points where I would like to add some information:

- TM4 -  you characterize this as no significant loss of information, but the information that the origin is the axis of rotation is significant.  Without the information that the origin is the axis of rotation, the origin cannot be determined.

- For GenDefs - I would prefer an empty section ("There are no general definitions") to complete removal.  If the section is completely removed, the reader will not know whether we forgot it, or if it is empty.  When following a template, it is better to have all sections and explicitly state when there is no relevant content.

**Comment by niazim3** [comment]
1. I can start working on the following changes to reduce discrepancies in the logs so it becomes easier to focus on the non-trivial changes:

Chipmunk:
- reinserting the empty General Definitions section
- update stable for the semi -descriptive names for the assumptions (the other examples no longer have assumptions listed as A1, A2, A3, A4...)

GlassBR:
- DD formatting (spacing, `symbol = expr` vs `expr`)

Should I work in the Devi branch? Branch off of the Devi branch that'll be branched back into the Devi branch? @szymczdm 

***
2. 
Would the addition of the text "entered by the user" from the stable description be considered trivial? Perhaps such text can be automatically appended to any variables that are present in lists of inputs or input data constraint tables?

**Comment by niazim3** [comment]
@smiths Should elements in the reports be crossed off as the branch is updated?

**Comment by samm82** [comment]
# TODO

## Trivial
- [ ] GlassBR DD equations
- [ ] GlassBR DD1 format
- [ ] Chipmunk SSD wording
- [ ] Chipmunk SCS link
- [ ] Chipmunk Assumptions links
- [ ] Chipmunk Assumptions descriptive names
- [ ] Chipmunk empty GenDefs section missing
- [ ] Chipmunk Input/Output and constraints in IMs

## Non-Trivial
- [ ] GlassBR TMs
- [ ] GlassBR IM2/IM3 - information loss
- [ ] GlassBR Data Constraints missing
- [ ] Chipmunk TM4 - information loss
- [ ] Chipmunk TM5 - information loss
- [ ] Chipmunk Assumptions/DDs for IMs removed -  information loss
- [ ] Chipmunk DDs missing
- [ ] Chipmunk Data Constraints missing

**Note:** This is a very bare-bones description of these issues - see above for full description

**Comment by samm82** [comment]
For the formatting of GlassBR DD1, should the DDs state if a quantity is unitless? @szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
All definitions should have the correct units -- and be 'unitless' if that is the correct unit.

**Comment by szymczdm** [comment]
Just jotting this down since it was part of a face-to-face conversation which hasn't been written down.

@niazim3 Yes you (and the others) can work directly on the Devi branch.

**Comment by niazim3** [comment]
It is desirable for the missing information to reappear where it originally was, correct? So adding the information to a derivation for a particular model is not an optimal solution?

**Comment by smiths** [comment]
@niazim3, I'm not sure what the question is referring to, but moving information to the derivation might be okay.  The original (manual) version isn't perfect.  There might be a better way to summarize the information.  If you have a better way to propose (equivalent is also okay), then let us know the details.  If it is better, or just as good, we can change the manual version to match the generated version.

**Comment by niazim3** [comment]
I should've mentioned I was referring to the missing information documented above for, for example, the instance models. 

## Proposal:
What if we were to add a "Notes"/"Additional notes" field to the models in question (i.e. `IMs`, `DDs`, `TMs`) that was just `[Sentence]`? 

https://github.com/JacquesCarette/Drasil/blob/bda79c7dae9c845c178e0c309dca68ec0f4bec4a/code/Example/Drasil/DocumentLanguage.hs#L188-L200

https://github.com/JacquesCarette/Drasil/blob/bda79c7dae9c845c178e0c309dca68ec0f4bec4a/code/Example/Drasil/DocumentLanguage/Definitions.hs#L139-L160

That way, if the extra information is not really derivation-related, it's not added to the derivations of the models and at the same time, the information is near the relevant symbols, units, descriptions, etc., making it hard for the user/reader to miss.

Although this is still hardcoding the information in, it is better than having the information lost, as @smiths mentioned earlier.

**Comment by smiths** [comment]
This sounds like a good idea to me @niazim3.  I would like to see an example of what the new documentation would look like, before propagating the idea too far, but it sounds like you are on the right track.  Maybe there will be something more clever that we can do in the future, but for now keeping the information through a Notes field makes sense.

**Comment by niazim3** [comment]
Thanks @smiths; I'm going to use GlassBR's calculation of capacity instance model as an example:

Current stable: 
![image](https://user-images.githubusercontent.com/28247301/41995844-0f614092-7a21-11e8-87bc-8137d2e17b10.png)
 
Currently generated:
![image](https://user-images.githubusercontent.com/28247301/41995910-3a6b1236-7a21-11e8-9522-ae5e8a3b485f.png)

Proposed change*:
![image](https://user-images.githubusercontent.com/28247301/41996273-5c264b24-7a22-11e8-9e77-2b95a87047e4.png)

* the row header can be called "Additional Notes" or just "Notes"

**Comment by JacquesCarette** [comment]
While we're at it, we might consider making the description back into a paragraph?

I notice we've lost the 'synonym' part of `LR`.

**Comment by niazim3** [comment]
The 'synonym' part of `LR` can be added as a sentence in the notes section for now. (Although, noticed that #166 and the [design choices wiki](https://github.com/JacquesCarette/Drasil/wiki/Design-Choices) makes it seem as if such information is something that would rather be foregone to avoid ambiguity.)

Is it standard practice to keep the Description as a paragraph? The list looks slightly easier to read, but that may be just my personal preference.

**Comment by JacquesCarette** [comment]
Paragraph or otherwise is a style issue. I kind of liked the table to be smaller -- and you find the current layout as easier to read.  Which says to me that this should be an option!  [Please file an issue]. For simplicity, we can keep things as is.

And hurray for the wiki!  Ok, I now agree with my old self rather than the manual version [and my self of 14 minutes ago], let's forego synonyms!

**Comment by smiths** [comment]
The proposed Notes field looks good to me.  (I also prefer the list version of Description.  😄)

Please go ahead and propagate the addition of the Notes field.  You should probably create a new issue for this change.

**Comment by niazim3** [comment]
As of 07cc70e, the log for GlassBR no longer points to discrepancies between the generated and stable files that indicate that information is being lost.

Instead, the discrepancies are: 
```
364c364
<               \item{$is\_safe1$ is true when calculated probability is less than tolerable probability (Unitless)}
---
>               \item{$is\_safe1$ is the true when calculated probability is less than tolerable probability (Unitless)}
390c390
<               \item{$is\_safe2$ is true when load resistance (capacity) is greater than load (demand) (Unitless)}
---
>               \item{$is\_safe2$ is the true when load resistance (capacity) is greater than load (demand) (Unitless)}
705a706,707
> \\ \midrule \\
> Notes & 
828a831,832
> \\ \midrule \\
> Notes & 
1186c1186
...
```
, which leads me to ask:

1. Are the empty "Notes" headings in the table alright? (i.e. should the generated version be copied into the stable version in this respect)

2. The "is the" automation has worked for all symbol descriptions so far, but it sounds awkward for the `is_*` variables. Should a new issue be opened for that and stable be updated for now to contain the awkwardly-worded descriptions?

**Comment by smiths** [comment]
Rather than an empty "Notes" entry in the table, can we display "not applicable" when there are no contents?  If many of the "Notes" fields are empty, this might start to feel like a waste of space.  In that case, it might be better to just not display this field when the content is empty.

As far at the "is the" goes, it is wrong to say "is the true."  I think you will have to create an issue for this.

Glad to hear that the information is no longer being lost in the generated version.  😄

**Comment by JacquesCarette** [comment]
We should definitely not display empty Notes sections. Whatever the data-structure is for Notes should be such that being empty can be detected.

**Comment by niazim3** [comment]
@JacquesCarette @smiths So it would be ideal if no field is displayed if the content is empty, but for now saying "not applicable" when there are no contents is fine?

**Comment by JacquesCarette** [comment]
For Notes, yes. [This is not a blanket statement, as for some fields it would be an error if they are empty]

**Comment by elwazana** [comment]
@JacquesCarette @smiths I was wondering for the Devi branch, one of the last things to do for stable is to correct the spacing issue in the DDs of GlassBr.

Stable:
![](https://user-images.githubusercontent.com/35268928/41603397-dd7473be-73aa-11e8-9802-95c6dad6fbc3.png)

Generated:
![](https://user-images.githubusercontent.com/35268928/41603439-f29784b6-73aa-11e8-835e-9a421c8c5118.png)

Which of these if prefered? Also should this be an option the user can make similar to #724?

**Comment by JacquesCarette** [comment]
I definitely prefer the compact version. There are likely many more options for display that I would wish to implement before this one... if ever.

**Comment by niazim3** [comment]
I think we can mention this discrepancy in #724 and update stable to match the generated versions for now...
Or would it be better to change the spacing in the generated html version to be more compact? @JacquesCarette

**Comment by smiths** [comment]
I agree that the compact version is preferable.  If the boxes get too big, we may have to deal with a box that is bigger than the page.  This sounds like a headache we want to avoid.

**Comment by JacquesCarette** [comment]
I thought this was the LaTeX... in any case, it would be good to investigate the reason why it is not compact. If it is a trivial fix, do it. If it isn't, then open an issue (and accept the current sub-optimal version)

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I made a change when adding Notes to the Chipmunk example was 
 de-capitalization of the titles:
https://github.com/JacquesCarette/Drasil/blob/46660f8943f5aafc703469a267ae5c312b62d5ac/code/stable/gamephys/Chipmunk_SRS.html#L1228

Was originally `Newton's Second Law of Motion`, I was just wondering if you guys have a preference for this?

**Comment by elwazana** [comment]
@smiths  For the Chimpmunk differences between Generated and Stable, I wanted to ask which of the following you would like to have as the introductory paragraph for Data Definitions:

_This section collects and defines all the data needed to build the instance models._
vs.
_This section collects and defines all the data needed to build the instance models. The dimension of each quantity is also given._

**Comment by smiths** [comment]
@elwazana, as far as capitalization goes, we want it to be consistent.  It is best if every title is capitalized with the same rules.  Ideally, this would be a configurable parameter for the generated documentation.  

As for the introductory paragraph for the data definitions, I like the first option.  The point about the dimensions seems arbitrary and tacked on.  If we are going to list the fields of the data definitions, we should list all of the fields.  (This (listing all the fields) is something else that could conceivable be configurable, but it isn't a high priority.  Maybe we would have an option of verbose versus not verbose?)

**Comment by JacquesCarette** [comment]
Agreed on all points.

**Comment by niazim3** [comment]
Just a few more changes originating from/discussed for the Devi branch were made in PR #743. Commit 19f3ea2 specifically changes the output from 
![image](https://user-images.githubusercontent.com/28247301/42226397-dcbad028-7eac-11e8-96e3-a2c25f76a08b.png)
to 
![image](https://user-images.githubusercontent.com/28247301/42226383-d4d7cdca-7eac-11e8-86ef-93c5c30bd0a2.png)
(added indents). I don't think the indents can be removed without making changes to the .css files, so these changes can be kept or requested for updates at your discretion @szymczdm @JacquesCarette ...

Other than that, I believe this issue can be closed.

**Comment by JacquesCarette** [comment]
I do think the indents should be removed.

**Comment by smiths** [comment]
I agree that the indents should be removed.  Other than that, it looks good.

Actually, can we make one small (I assume) change.  Can the Notes field please come right after the Description field?  The notes are going to be related to the Description.  Also, ending with Source and RefBy is fairly standard at this point.

**Comment by niazim3** [comment]
Thanks for the feedback! The placement of notes has been updated as of commits 
b032040...e1e9911.

I'm going to draw @halonazhao's attention to the above commits and comment, since she was updating the other examples in her branch for the addition of notes as well.

**Comment by smiths** [comment]
Looks good.
