### ISSUE TITLE
Removing Sentence constructors

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#700]
@szymczdm @JacquesCarette Hello Dr. Carette and Dan, @samm82 and I were looking through notes folder for stuff we could possibly work on and we were wondering what you meant by:
https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/notes/DrasilPotentialTasks.txt#L87

Do you mean these?
https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Language/Drasil/Spec.hs#L39-L86

**Comment by JacquesCarette** [comment]
I meant both those (which are almost always used as hacks, especially `sParenNum` and `sSqBr`). I also think that some of the cases of `Spec` perhaps shouldn't be there.  But that requires more analysis & thinking. I have already removed the ones that were easy to remove.

**Comment by samm82** [comment]
## sParenNum

Used here for a list:
https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Example/Drasil/GlassBR/Assumptions.hs#L44-L55

## sSqBrNum

Used here for a reference:
https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Example/Drasil/GamePhysics/Body.hs#L192-L197

https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Example/Drasil/GlassBR/Body.hs#L396-L398

https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Example/Drasil/SWHS/Body.hs#L833-L837

I'm not really sure how these usages are hacks.

**Comment by samm82** [comment]
1. So should we define a new function for building a list and could we use `sParenNum` to achieve that?
2. @elwazana says that the change for `sSqBrNum` will be made once `Label` is fully implemented. Is that what you are referring to?

**Comment by JacquesCarette** [comment]
1. Yes and yes. [`sParenNum` used internally in printing is fine. But it should not be exported]
2. Yes.

**Comment by samm82** [comment]
Some observations (This probably isn't the best place for this - we might need to move it.) This is what the text reads now, in both gen and stable:

"glassTy: The standard E1300-09a for calculation applies only to monolithic, laminated, or insulating glass constructions of rectangular shape with continuous lateral support along[.] one, two, three, or four edge() This practice assumes <that (1)> the supported glass edge for two, three and four-sided support conditions are simply supported and free to slip in plane; (2) glass supported on two sides acts as a simply supported \<beam and> (3) glass supported on one side acts as a cantilever."

1. The period in brackets shouldn't be there. - Correct in caseStudies
2. The empty parentheses should contain "s."- Correct in caseStudies
3. There should be a colon between "that" and "(1)" (see angled brackets).
4. There should be a semicolon between "beam" and "and" (see angled brackets).

---

We also have a design proposal for an `sList` function. It will take a list of `[Sentence]` and return a `Sentence`. Ie:

[a, b, c] -> (1) a; (2) b; and (3) c (if commas exist in any of a, b, or c) or 
[a, b, c] -> (1) a, (2) b, and (3) c (if commas don't exist in any of a, b, or c).

It will make a list from 1 to the length of the list, map `sParenNum` onto it, intersperse it with the original list (ie. [(1), a, (2), b, (3), c] all sentences), then recursively concatenate pairs of them with spaces and use the `foldlList` function (that should probably be pulled out and use semicolons if commas are present in the inputs):

https://github.com/JacquesCarette/Drasil/blob/628b54d0e17d0b818be0c36480416e5bf37a2139/code/Language/Drasil/HTML/Print.hs#L441-L444

to concatenate them each pair (ie. "(1) a") and add the "and" before the last one.

**Comment by JacquesCarette** [comment]
I would definitely not put such a combinator in `L.D.HTML.Print`. It's a hack if that is where `foldlList` is now.

Such a combinator makes sense, but it should be parametrized by a separator as well as a means of decorating it with "numbers" (which could be a), b), c) BTW).

This is exactly the kind of thing that the higher-level enumeration structures are built to handle. So this piece of text should be more structured, rather than hand-printed into a low-level `Spec`.

**Comment by samm82** [comment]
1. Where should `foldlList` be moved to? Probably the same place as `sList`, right?
2. What do you mean by "separator"? The numbering system or the commas/semicolons?
3. How many numbering systems should be supported? Numbers, lowercase, uppercase, Roman numerals / periods -> 1., parenthesis -> 1), parentheses -> (1)?

**Comment by samm82** [comment]
As far as `sSqBrNum`, it just seems like the manifestation of smiths/caseStudies#31, which can easily be fixed. @smiths @JacquesCarette

**Comment by smiths** [comment]
@samm82 I agree.  There might be other cases where we want square brackets around a sentence, but when that sentence is citation information, the format of the citation should be automatic.  We definitely should remove all hard-coded citation numbers in the Drasil code.  These aren't maintainable.

**Comment by JacquesCarette** [comment]
1. There are already things named `fold?List` [replace the ? with either nothing or 'l' or 'r'], probably belongs with them.  
2. By "separator" I mean the commas/semicolons.
3. Well, all of the ones that HTML and LaTeX support natively...

**Comment by samm82** [comment]
Just to clarify - as is, this example is an inline list - that should be preserved, correct? @JacquesCarette @smiths

**Comment by smiths** [comment]
Yes, we want to preserve the idea of in-line lists.  I also agree that the generated html or latex code should use these languages in-line list code.

**Comment by samm82** [comment]
I'm trying to add a package to the TeX preamble that will allow for changing the numbering system and for inline lists, and I've updated the stable for the examples, but log.log isn't empty and I'm not sure why.

Commit: 4e8d164

**Comment by JacquesCarette** [comment]
`log.log` is badly named -- that's the logfile for 'tiny' !!!  Maybe open an issue to rename that, so that it's not so hard to debug in the future.

**Comment by samm82** [comment]
@JacquesCarette the only function that exists as you describe it is `foldlList` and is defined here:

https://github.com/JacquesCarette/Drasil/blob/4f124660124f4d86d7407af17494662e21533fc1/code/drasil-data/Data/Drasil/SentenceStructures.hs#L56-L60

It is also in HTML/Print (as found out before), but only locally, and slightly different

https://github.com/JacquesCarette/Drasil/blob/4f124660124f4d86d7407af17494662e21533fc1/code/drasil-lang/Language/Drasil/HTML/Print.hs#L461-L464

---
Can we define our new list-making function with `foldlList` in SentenceStructures?

**Comment by szymczdm** [comment]
I see you edited your last comment, but what's the status on this issue then?

**Comment by samm82** [comment]
I think this might have to wait until after the merge of #906, but we'll have to implement a way to print a list using the methods native to LaTeX and HTML - I'll start by compiling a list of what common methods there are so we can at least start with those.

**Comment by samm82** [comment]
After looking around for a while, it doesn't look like HTML allows for inline lists using parentheses as we desire, so I think we should hardcode this, but more generally than we are right now. We should make a `foldInlineNumbered` function that would use `sParenNum` (but not export it) that would work with `foldlList` as mentioned before. Should we still try and use LaTeX's inline list functionality? This would be done via `\begin{enumerate*}[label=(\arabic*)]` using `\usepackage[inline]{enumitem}`.

**Comment by samm82** [comment]
And should the separators be passed in our automatically generated? I think they should be automatically generated, but it might be easier to manually input them.

**Comment by samm82** [comment]
I went ahead and implemented `EnumType` in 086536e71 and made the function look a little nicer. There is a helper function `makeList` that isn't exported. Do we want roman numerals to be used? Because that would be a little bit messier, but very possible.

Also a note, the "separator" that @JacquesCarette mentioned earlier has to be passed in as a `Sentence`, so currently that is being done by `S ";"`, but this could be changed.

**Comment by samm82** [comment]
## TODO

- [ ] Revert commit 4e8d164cd745cc737bf (if we are sure we want to hardcode)
- [ ] Add `WrapType`
- [ ] Add `SepType` -> remove `S ";"` hack
- [ ] Add Roman Numerals to `EnumType`?

**Comment by samm82** [comment]
@JacquesCarette Would you like roman numerals to be a feature, or should we wait until we want to actually use it?

**Comment by JacquesCarette** [comment]
If it takes < 1 hour to implement, go ahead, otherwise let's wait.

**Comment by samm82** [comment]
Traditional Roman numerals go up to 3'999, but given that upper and lowercase letters both have 26 characters each, should I cap Roman numerals at 100? I already have a Haskell function that generates Roman numerals that I did as an exercise

**Comment by JacquesCarette** [comment]
I believe that both LaTeX and HTML know how to generate Roman numerals, as an option to their generators of enumerations. So there should be no need for us to generate these!

**Comment by samm82** [comment]
But the current implementation of inline lists involved hardcoding the enumerators. Can we still use the LaTeX and HTML Roman numerals? I would assume they would still have to be hardcoded

**Comment by JacquesCarette** [comment]
Sigh. Then the current implementation of lists should be fixed, at least in LaTeX. Not sure about HTML, we might have to hardcode. Sigh.

**Comment by samm82** [comment]
I just assumed that since we'd have to hardcode in HTML, instead of having two separate implementations, we would just hardcode both, especially since it was hardcoded even more so originally. So what should we do now? We could also just wait on adding Roman numerals since we don't use them yet and keep the hardcoding, but that would essentially result in replacing a hack with a lesser hack. Or, we could add an `InlineList` data type somewhere and hardcode it in HTML (using the new `foldlList` function and moving `foldlEnumList` to `drasil-printing`) and use the native LaTeX?

**Comment by JacquesCarette** [comment]
I think it would be simpler to just wait on adding roman numerals.

**Comment by samm82** [comment]
So to reiterate the original issue, `sParenNum` has been removed (thanks to the new list function(s)), and `sSqBrNum` will/should probably be removed after `Label` is implemented. Are there any other functions that can be (relatively easily) removed, or should we leave it to focus on more crucial work by marking it with the "waiting on label" label to revisit later?

**Comment by samm82** [comment]
I'll also open a PR for the branch where the change was made (if you're sure the hardcoding is OK, at least for now).

**Comment by JacquesCarette** [comment]
Leave it to focus on more crucial work. And hardcoding is ok for now.

**Comment by samm82** [comment]
It seems as if Spec.hs has been deleted and the only helper function of this sort is `sParen` (in Sentence.hs), so I'm closing this issue.

**Comment by smiths** [comment]
Nice to see you jumping right back in @samm82!  I can tell that @JacquesCarette and I better get thinking of additional tasks to keep you busy.  😄
