### ISSUE TITLE
GlassBR: Fix Hardcoded References in SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#742]
A continuation of smiths/caseStudies#31 - some references are being hardcoded instead of linked.

## TODO

- [ ] Characteristics of Intended Reader
- [ ] Terminology and Definitions
  - [ ] Glass Type
  - [ ] Load
- [ ] Calculation of Capacity IM

---
Note: `cc'` takes a `Sentence` instead of a `String`

**Comment by samm82** [comment]
@elwazana Says this can't be fixed until `Label` is fully implemented.

**Comment by elwazana** [comment]
@JacquesCarette Should this issue be closed, as this is the remove `acro-` functions issue #312?

**Comment by JacquesCarette** [comment]
Well, are all the tasks in the TODO done?  It would be nice to explicitly have checkmarks there, to give higher confidence that they have been done.

**Comment by elwazana** [comment]
Ok if that's the case should I add-on to the checklist above?

**Comment by szymczdm** [comment]
Let's keep this issue up-to-date (ie. add on to the checklist above).

**Comment by JacquesCarette** [comment]
There are more things to do then?

**Comment by elwazana** [comment]
@JacquesCarette @szymczdm I've discussed this issue with @samm82, I misunderstood what he described the issue as to me initially. The issue is referring to the use of `sParenNum` which produces, [4], not an actual link. 

This should still be eventually fixed once Label is implemented fully.
