### ISSUE TITLE
Empty Source Fields

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#947]
Theoretical Models, General Definitions, Data Definitions, and Instance Models have a `Source` field that is sometimes empty when it should be filled with "--" to indicate the lack of information is intentional.

# TODO

- [x] Switch from `[Citation]` to `[Reference]` (#1295)
- Create constructors for intentionally-empty Source fields and modify old constructor to throw an error if Source Field is empty
    - [x] TM (#1310)
    - [x] DD (#1329)
    - [x] IM (#1327)
    - [x] GD (#1335)
- Chipmunk
   - [x] All TMs (#1310)
   - [x] All DDs (#1329)
   - [x] All IMs (#1327)
- NoPCM
   - [x] Simplified rate of change of temperature GD (#1335)
- SSP
   - [x] "Sums of the interslice normal forces" and "Sums of the interslice normal water forces" DDs (#1329)
   - [x] Heights of the left/right side of slices DDs (#1329)
- SWHS (same as NoPCM - probably one change will fix both)
   - [x] Simplified rate of change of temperature GD (#1335)
- Tiny
   - [x] DDs -> source code (#1329)
- [x] Display "--" if Source field empty (#1335)
- [x] Add design approach to Wiki

**Comment by smiths** [comment]
Sounds good.  Hopefully labels are working soon.

**Comment by JacquesCarette** [comment]
Hmm, I wonder what we should do when a source or refby is empty. Should that be an error?  If not, then maybe that part of the display should be omitted? We should make an explicit decision about which fields of these various things are *required*.

**Comment by smiths** [comment]
Good question @JacquesCarette.  If source or refby are empty, the first question should be whether the lack of content is a mistake.  In some cases this information was left blank in the "manual" examples when it shouldn't have been.  However, I don't think I would go so far as to say a lack of content is an error. It feels more like a "warning" than an error.  

Not displaying the fields when they are empty is the cleanest looking solution.  I would be okay with that, although I marginally prefer the visual reminder of including the field, but explicitly showing the contents are empty, maybe with a dash.  The explicit dash shows the reader that this was considered and still left blank.  This is a clear indication that the content really is empty, and not just forgotten.

**Comment by JacquesCarette** [comment]
As long as we do not have "easy combinators" for leaving those parts empty [because then people will use them without being forced to think about it], we could indeed just put -- as an indication of an explicit choice.

**Comment by smiths** [comment]
Sounds reasonable.

**Comment by samm82** [comment]
@smiths What should the workflow be for this issue? At least for the sake of this issue, can I assume these fields are accurate in caseStudies and just ensure that the information matches up (add source/refby if missing or "--" if not applicable)?

**Comment by smiths** [comment]
@samm82, yes, you can assume that the case studies are correct.  I'm sure they will need future review, but capturing the current information should be the first step.

**Comment by samm82** [comment]
The way the Source field is handled now is that the `TM` (or whatever chunk) will take a `[Reference]`. It was mentioned on the previous issue that this shouldn't default to "--", since the whole purpose of "--" is indicating that the field is empty intentionally. However, since the chunks take a `[Reference]`, to indicate that there shouldn't be anything, indicating that the list should be empty involves creating an "empty reference", which doesn't sound like the greatest solution.

I think we should implement the chunks to take a `Maybe [Reference]`, where `Nothing` indicates it being intentionally empty, `Just []` indicating an oversight, and `Just refs` indicating that the references are the contents of `refs`. Thoughts? @smiths @JacquesCarette

**Comment by smiths** [comment]
@samm82, I agree with your thought process.  Whether this is the best design solution is a question that @JacquesCarette would be better for answering.

**Comment by samm82** [comment]
Before I changed anything, TM used `[Reference]` and DD used `[Citation]` should (maybe in a different issue/branch) make these consistent? If so, which one should be used? @smiths @JacquesCarette From looking at the constructors in Reference.hs, `Reference`s are built from `Citation`s, so it looks like `Citation` should be used.

Once again, what I thought was a simple issue has snowballed. 😂

**Comment by JacquesCarette** [comment]
I see now that my comment on a check-in crossed with this discussion. The advice there still stands.

The problem with the `Maybe` solution is as you say above: it enables `Just []` as a valid entry, which should then be considered an error. It feels odd to me.

I think we need to think more deeply about the difference between "no references on purpose" and "no references" to see if there truly is a meaningful difference. I am not starting to doubt it, old discussion notwithstanding.

**Comment by samm82** [comment]
From above:
> As long as we do not have "easy combinators" for leaving those parts empty [because then people will use them without being forced to think about it], we could indeed just put -- as an indication of an explicit choice.

I think not using the `Maybe`, and always printing "--" with an empty list will let people omit references "without being forced to think about it".

**Comment by JacquesCarette** [comment]
I think one of the problems here, and why we're having some difficulty discussing this, is that the "implementation details" are visible to the 'user of Drasil'. We shouldn't be arguing about using Haskell data-structures as a way to enforce our invariants.  Well, ok, sometimes that is a good idea. But here, it seems not.

I think a much better design is to use, exclusively, smart constructors for these things. They should be 'meaningful' names. And one should communicate 'no references on purpose' while the other should enforce (at run time, through a check) that there is at least one reference and throw an error otherwise. Then the low-level data-structure can just be `[Reference]`.

**Comment by smiths** [comment]
This sounds like some good wisdom for guiding design choices.  @samm82, when this issue is closed, please take some time to distill the design principles being used and put them in the contributor's guide.

**Comment by samm82** [comment]
@JacquesCarette That sounds like a better implementation - I'll work on that
@smiths Will do 👍

**Comment by samm82** [comment]
@smiths I don't remember where I saw it, but I made a note that the source in the DDs for Tiny is the source code. (Right now I just used the "noRefs" constructor.) With our current infrastructure, we can't just just display "source code". Is there a reference for the code that we could add to Tiny, or should we not bother?

**Comment by samm82** [comment]
@JacquesCarette Right now, the constructors for IMs are `im'` which doesn't take a derivation, and `im''` which does. Should I refactor these to take all combinations (ie, `im`, `imNoRefs`, `imNoDeriv`, `imNoRefsNoDerivs`)? Or should I just merge these two functions (and pass an empty list for derivations), and we can revisit not passing derivations with a similar approach to this one throughout all the examples?

**Comment by JacquesCarette** [comment]
yes, please refactor those combinators as you suggest.

**Comment by smiths** [comment]
@samm82, I think we are best off going with your no reference option ("noRefs").  The actually reference would be the theory manual for a fuel pin analysis thermal analysis that we have, but we don't have permission to make the manual available, and it isn't a public document.  Tiny isn't really meant to be a "real" example, so just leaving it as noRefs is fine.
