### ISSUE TITLE
ConceptInstance Tracking Issue

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#985]
This issue is the successor to #562. 
This issue aims to track all that is remaining to do from the design(s) outlined in #562 before it is complete. The list of items is general and may be split in to smaller subitems when I start working on them.

- [x] Deferred `ShortName`s
- [x] Add remaining SRS domains to docLang.
- [x] Propagate `ConceptInstance` through ALU (of `ALUR`) for NoPCM
- [x] Propagate `ConceptInstance` through all examples
- [x] Switch `ConceptInstance` to using `Label`
- [x] Add support to pull `ConceptInstance`s from the assumption domain when using `SCSProg`'s `Assumptions` constructor in docLang.
- [x] Remove (in pieces) `ALUR` and all the levels (like `ReqChunk` and `Requirements`) which contributed to the original embedding.

**Comment by Mornix** [comment]
#1148 completed this. Closing.
